-- MySQL Script generated by MySQL Workbench
-- Fri Oct 30 00:45:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `idProfessor` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `calendar link` VARCHAR(45) NULL,
  PRIMARY KEY (`idProfessor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `idStudent` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NULL,
  `photo` LONGBLOB NULL,
  `email` VARCHAR(45) NULL,
  `AcademicDepartment` VARCHAR(45) NULL,
  PRIMARY KEY (`idStudent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`replyAction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`replyAction` (
  `idreplyAction` INT NOT NULL,
  `resultComment` TEXT NULL,
  PRIMARY KEY (`idreplyAction`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`askAction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`askAction` (
  `idaskAction` INT NOT NULL,
  `question` TEXT NULL,
  `replyAction_idreplyAction` INT NOT NULL,
  PRIMARY KEY (`idaskAction`),
  INDEX `fk_askAction_replyAction1_idx` (`replyAction_idreplyAction` ASC) VISIBLE,
  CONSTRAINT `fk_askAction_replyAction1`
    FOREIGN KEY (`replyAction_idreplyAction`)
    REFERENCES `mydb`.`replyAction` (`idreplyAction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Education` (
  `Professor_idProfessor` INT NOT NULL,
  `Student_idStudent` INT NOT NULL,
  PRIMARY KEY (`Professor_idProfessor`, `Student_idStudent`),
  INDEX `fk_Professor_has_Student_Student1_idx` (`Student_idStudent` ASC) VISIBLE,
  INDEX `fk_Professor_has_Student_Professor_idx` (`Professor_idProfessor` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_has_Student_Professor`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Student_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`questionning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questionning` (
  `Student_idStudent` INT NOT NULL,
  `askAction_idaskAction` INT NOT NULL,
  PRIMARY KEY (`Student_idStudent`, `askAction_idaskAction`),
  INDEX `fk_Student_has_askAction_askAction1_idx` (`askAction_idaskAction` ASC) VISIBLE,
  INDEX `fk_Student_has_askAction_Student1_idx` (`Student_idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_Student_has_askAction_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_askAction_askAction1`
    FOREIGN KEY (`askAction_idaskAction`)
    REFERENCES `mydb`.`askAction` (`idaskAction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Answering` (
  `Student_idStudent` INT NOT NULL,
  `replyAction_idreplyAction` INT NOT NULL,
  PRIMARY KEY (`Student_idStudent`, `replyAction_idreplyAction`),
  INDEX `fk_Student_has_replyAction_replyAction1_idx` (`replyAction_idreplyAction` ASC) VISIBLE,
  INDEX `fk_Student_has_replyAction_Student1_idx` (`Student_idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_Student_has_replyAction_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_replyAction_replyAction1`
    FOREIGN KEY (`replyAction_idreplyAction`)
    REFERENCES `mydb`.`replyAction` (`idreplyAction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
